#!/usr/bin/env node
'use strict';

/**
 * Build a self-contained app for ONE game, inside that game's folder.
 *
 *   npm run publish <id>
 *
 * Generates games/<id>/app/ — a full React Native + Android project with the
 * embedded Node server (framework + this game) baked in, and App.tsx pointed at
 * <id>. framework/native/app-template/ is the TEMPLATE this is copied from. After
 * this, each game owns its own runnable app; build it from games/<id>/app.
 *
 * It also patches the (shared) pairing worker for <id>. It does NOT build the APK
 * or deploy the worker — that needs your Android SDK / Cloudflare account.
 *
 * games/<id>/app/ is generated output (gitignored) — re-run publish anytime.
 */
const fs = require('fs');
const path = require('path');

const id = (process.argv[2] || '').trim();
if (!/^[a-z][a-z0-9-]{1,30}$/.test(id)) { console.error('Usage: npm run publish <id>'); process.exit(1); }

const root = path.join(__dirname, '..');
const gameDir = path.join(root, 'games', id);
const cfgPath = path.join(gameDir, 'game-config.json');
if (!fs.existsSync(cfgPath)) { console.error(`games/${id}/game-config.json not found.`); process.exit(1); }

const template = path.join(root, 'framework', 'native', 'app-template');
if (!fs.existsSync(template)) { console.error('Template framework/native/app-template not found.'); process.exit(1); }

const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
const theme = cfg.theme || {};
const esc = (s) => String(s == null ? '' : s).replace(/'/g, "\\'");
const title = esc((cfg.text && cfg.text.APP_TITLE) || id);
const accent = esc(theme['--game-accent'] || '#00d2ff');
const bg = esc(theme['--game-primary'] || '#060a14');
const tagline = esc((cfg.text && cfg.text.APP_TAGLINE) || 'TV GAME');
const motion = cfg.supportsMotion === true;

// dirs we never copy (build caches, deps) — regenerated by `npm install` / gradle
const SKIP = new Set(['node_modules', 'build', '.gradle', '.cxx', '.idea']);
const appDir = path.join(gameDir, 'app');

// Manual recursive copy that skips given dir names. Needed for the game→app embed,
// because the dest lives inside the source (games/<id>/app) and fs.cpSync refuses
// to copy a directory into a subdirectory of itself.
function copyDir(src, dest, skip) {
  fs.mkdirSync(dest, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    if (skip.has(e.name)) continue;
    const s = path.join(src, e.name), d = path.join(dest, e.name);
    if (e.isDirectory()) copyDir(s, d, skip);
    else fs.copyFileSync(s, d);
  }
}

console.log(`Publishing "${id}" → games/${id}/app/`);

// 1. fresh copy of the template shell
fs.rmSync(appDir, { recursive: true, force: true });
fs.cpSync(template, appDir, { recursive: true, filter: (src) => !SKIP.has(path.basename(src)) });

// 2. embed framework (minus native/rendezvous) + just this game
const np = path.join(appDir, 'nodejs-assets', 'nodejs-project');
fs.rmSync(path.join(np, 'framework'), { recursive: true, force: true });
fs.rmSync(path.join(np, 'games'), { recursive: true, force: true });
fs.cpSync(path.join(root, 'framework'), path.join(np, 'framework'), {
  recursive: true,
  filter: (src) => {
    const rel = path.relative(path.join(root, 'framework'), src);
    return !rel.startsWith('native') && !rel.startsWith('rendezvous') && !SKIP.has(path.basename(src));
  },
});
copyDir(gameDir, path.join(np, 'games', id), new Set([...SKIP, 'app']));  // skip app/ to avoid self-nest

// 3. point App.tsx at this game
const appTsx = path.join(appDir, 'App.tsx');
let t = fs.readFileSync(appTsx, 'utf8');
t = t.replace(/const GAME_ID = '[^']*';/, `const GAME_ID = '${id}';`)
     .replace(/const BRAND = \{[^}]*\};/, `const BRAND = { name: '${title}', accent: '${accent}', bg: '${bg}', tagline: '${tagline}' };`)
     .replace(/const USE_MOTION = (?:true|false);/, `const USE_MOTION = ${motion};`);
fs.writeFileSync(appTsx, t);

// 3b. per-game Android applicationId so two published games install side-by-side.
// Patch ONLY applicationId — NOT namespace. namespace must stay com.cricketdash to match
// the Kotlin package (BuildConfig is generated under the namespace; changing it breaks the
// com.cricketdash MainApplication.kt). applicationId (install id) may differ freely.
const appId = (cfg.android && cfg.android.appId) || ('com.tvgame.' + id.replace(/[^a-z0-9]/g, ''));
const gradle = path.join(appDir, 'android', 'app', 'build.gradle');
if (fs.existsSync(gradle)) {
  let g = fs.readFileSync(gradle, 'utf8')
    .replace(/applicationId\s+"[^"]*"/, `applicationId "${appId}"`);
  fs.writeFileSync(gradle, g);
}

// 3c. APK launcher NAME = the game title (was "cricswing"). + tint the default
// adaptive-icon background to the game accent so the icon isn't CricSwing-branded.
const strings = path.join(appDir, 'android', 'app', 'src', 'main', 'res', 'values', 'strings.xml');
if (fs.existsSync(strings)) {
  let s = fs.readFileSync(strings, 'utf8')
    .replace(/(<string name="app_name">)[^<]*(<\/string>)/, `$1${title}$2`);
  fs.writeFileSync(strings, s);
}
const iconColors = path.join(appDir, 'android', 'app', 'src', 'main', 'res', 'values', 'ic_launcher_colors.xml');
if (fs.existsSync(path.dirname(iconColors))) {
  fs.writeFileSync(iconColors,
    `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n  <color name="ic_launcher_background">${accent}</color>\n</resources>\n`);
}

// NOTE: the pairing site (framework/rendezvous/) is a SINGLE central hub deployed
// once for ALL games — publish no longer patches it per game. Point each game at it
// via RENDEZVOUS_URL in game-config.json.

console.log(`  built games/${id}/app/ (App.tsx → '${id}', framework + game embedded)`);
console.log(`\nNext:`);
console.log(`  APK:  cd games/${id}/app && npm install && npx react-native run-android`);
console.log(`  Central pair site (deploy once for all games): cd framework/rendezvous && wrangler deploy`);
